/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf --transform 
Files: scene.gltf [134.1KB] > scene-transformed.glb [3.51MB] (-2518%)
Author: Heataker (https://sketchfab.com/Heataker)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/standard-drum-set-8d02d9cb0e0441ab96d799c8ca7eff50
Title: Standard Drum Set
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/drums.glb')


  useEffect(() => {
    return () => {
      // Clean up materials and geometries
      Object.values(materials).forEach((material) => {
        material.dispose();
      });

      Object.values(nodes).forEach((node) => {
        if (node.geometry) {
          node.geometry.dispose();
        }
      });
    };
  }, []);


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.DrumSet} position={[-0.426, 0, -0.004]} rotation={[0, Math.PI / 6, 0]} scale={0.75} />
    </group>
  )
}

useGLTF.preload('/drums.glb')
