/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf --transform 
Files: scene.gltf [83.5KB] > tesla.glb [380.32KB] (-355%)
Author: iSteven (https://sketchfab.com/OneSteven)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/tesla-model-3-117d7dbdd6f94df9886c42995cdd06db
Title: Tesla Model 3
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/tesla.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Capot013_Material017_0.geometry} material={materials.PaletteMaterial001} position={[-3.529, 80.378, -64.195]} rotation={[-1.579, -0.003, 0.01]} scale={98.981} />
      <mesh geometry={nodes.Capot010_Material016_0.geometry} material={materials.PaletteMaterial002} position={[-3.448, 46.392, -67.627]} rotation={[-1.579, -0.003, 0.01]} scale={98.981} />
      <mesh geometry={nodes.wheel003_Material013_0.geometry} material={materials['Material.013']} position={[101.126, -11.645, -263.104]} rotation={[-Math.PI / 2, 0, 0]} scale={1.441} />
      <mesh geometry={nodes.wheel003_Material012_0.geometry} material={materials['Material.012']} position={[101.126, -11.645, -263.104]} rotation={[-Math.PI / 2, 0, 0]} scale={1.441} />
      <mesh geometry={nodes.wheel003_Material011_0.geometry} material={materials.PaletteMaterial003} position={[101.126, -11.645, -263.104]} rotation={[-Math.PI / 2, 0, 0]} scale={1.441} />
      <mesh geometry={nodes.Capot_Material002_0.geometry} material={materials.PaletteMaterial004} position={[-3.841, 69.749, -100.531]} rotation={[-1.579, -0.003, 0.01]} scale={98.981} />
    </group>
  )
}

useGLTF.preload('/tesla.glb')
