/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 scene.gltf --transform 
Files: scene.gltf [268.4KB] > scene-transformed.glb [329.63KB] (-23%)
Author: Wesai (https://sketchfab.com/Wesai)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/udon-meal-aeadafce557445df8d852109f2794f6a
Title: Udon Meal
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useEffect } from 'react';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/udon.glb')

  useEffect(() => {
    return () => {
      // Clean up materials and geometries
      Object.values(materials).forEach((material) => {
        material.dispose();
      });

      Object.values(nodes).forEach((node) => {
        if (node.geometry) {
          node.geometry.dispose();
        }
      });
    };
  }, []);


  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cloth_00_mat_misc_0.geometry} material={materials.mat_misc} />
      <mesh geometry={nodes.table_mat_table_0.geometry} material={materials.mat_table} />
      <mesh geometry={nodes.sushi_00_mat_ingredients_0.geometry} material={materials.mat_ingredients} />
      <mesh geometry={nodes.cup_01_mat_bowl_0.geometry} material={materials.mat_bowl} />
    </group>
  )
}

useGLTF.preload('/udon.glb')
